#FROM registry.access.redhat.com/ubi9/ubi
FROM localhost/ubi9/ubi

ENV PHP_VERSION="8.2"
 
COPY bin/instalar-pacotes.sh /tmp
COPY pacotes/* /tmp
 
WORKDIR /tmp/
 
RUN chmod +x /tmp/instalar-pacotes.sh && \
    /tmp/instalar-pacotes.sh
 
ENV LANG="pt_BR.ISO-8859-1"
 
RUN sed -i -e 's/AllowOverride None/AllowOverride All/g' \
           -e 's/Listen 80/Listen 8080/g' /etc/httpd/conf/httpd.conf && \
    sed -i -e 's/;rlimit_files = 1024/rlimit_files = 2048/g' \
           -e 's/^;php_value\[opcache/php_value[opcache/' \
           /etc/php-fpm.d/www.conf && \
    mv /etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ssl.conf-disabilitado && \
    rm -vf /etc/httpd/conf.d/README /etc/httpd/conf.d/userdir.conf /etc/httpd/conf.d/welcome.conf
 
RUN mkdir -p /opt/tmp /mnt/sei/arquivos && \
    chown -R apache:apache /mnt/sei/arquivos && \
    chmod 2775 /mnt/sei/arquivos && \
    mkdir -p /var/log/sei /var/log/sip /run/php-fpm && \
    chown -R apache:apache /run/php-fpm

COPY configuracoes/99-tuning.conf /etc/sysctl.d/
COPY configuracoes/99-apache.conf /etc/security/limits.d/
COPY configuracoes/sei.conf /etc/httpd/conf.d/
COPY configuracoes/cron.conf /opt/tmp
COPY fontes/* /opt/
COPY bin/entrypoint.sh /opt/scripts/

RUN chmod +x /opt/scripts/entrypoint.sh

USER apache

WORKDIR /var/www/html

EXPOSE 8080
 
ENV CRON_ENABLED=false
ENV GEARMAND_ENABLED=false
ENV SUPERVISOR_ENABLED=false
ENV HTTPD_ENABLED=false

CMD ["/opt/scripts/entrypoint.sh"]

